"""
Conversation ORM model for storing conversation history.
"""

from sqlalchemy import Column, String, Integer, BigInteger, Text, TIMESTAMP
from sqlalchemy.sql import func
from app.database import Base

class Conversation(Base):
    """Conversation history table."""
    __tablename__ = "conversations"

    id = Column(BigInteger, primary_key=True, autoincrement=True, comment="Unique ID of the conversation record")
    question = Column(Text, nullable=False, comment="Question asked by the user")
    answer = Column(Text, nullable=False, comment="Answer generated by the model")
    created_at = Column(TIMESTAMP, server_default=func.current_timestamp(), comment="Conversation creation timestamp")